### ISSUE TITLE
Change autocomplete default

### ISSUE THREAD

**Issue by mskocik** [czubehead/bootstrap-4-forms#12]
Have you thought about setting `autocomplete` attribute false by default? In my experience it's more common to have it turned off? With many forms in app it's could get quite annoying.

**Comment by czubehead** [comment]
@mskocik no. Even though I do agree that 
>  With many forms in app it's could get quite annoying.

it isn't right to add an extra attribute nobody explicitly asked for.

One can relatively easily modify this behaviour with inheritance.
You would inherit `\Czubehead\BootstrapForms\Traits\BootstrapContainerTrait` and override all add* methods with custom ones (autocomplete=false), then inherit `\Czubehead\BootstrapForms\BootstrapForm`, and use the trait. You may also have to do the same with `\Czubehead\BootstrapForms\BootstrapContainer`
