### ISSUE TITLE
nette 3 support

### ISSUE THREAD

**Issue by dakorpar** [czubehead/bootstrap-4-forms#24]
Any plan for nette 3 support?
Anyone still maintaining this? I don't see any activity...

**Comment by AliAmjid** [comment]
That would be good. 

It shouldn't be a big problem to update it for nette 3. Maybe I will try.

**Comment by mskocik** [comment]
I have fork which is Nette 3.0 ready:
[https://github.com/mskocik/bootstrap-4-forms](https://github.com/mskocik/bootstrap-4-forms)

**Comment by chapcz** [comment]
@mskocik - pull request?

**Comment by mskocik** [comment]
@chapcz Pull request won't be merged, because @czubehead is no longer active ⚰️. That's the only reason I created my own fork.

**Comment by dakorpar** [comment]
sadly I completelly stopped using project since it's abandoned, although I found it really interesting...
@mskocik maybe best would be to see with https://github.com/contributte they're usually interested into taking packages and maintain them @f3l1x ? 
It's just a suggestion so this doesn't die...

**Comment by f3l1x** [comment]
Would you @dakorpar maintain and upgrade this package if it will be in @contributte?

**Comment by dakorpar** [comment]
@f3l1x I need few days to investigate a bit and then I will reply

**Comment by mskocik** [comment]
@dakorpar Yes, good idea, if someone would mantain it. I won't have time for it myself, so feel free to grab all commits from my fork. Basically all commits from september 2019 are related to nette 3 upgrade.

**Comment by dakorpar** [comment]
I'll take the bullet and I will maintain it. @f3l1x 
Just switched on new project back to this forms and works nicelly so I'll be using package on my project and I'm ok with maintaining it then.
@mskocik I'll take some commits from you, DateTime inputs are still not compatible I'll fix it. 
As soon as @f3l1x forks this to contributte and give me rights I'll upgrade it so it supports nette 3

**Comment by mskocik** [comment]
@dakorpar Yes, that's possible because I've actually never used the date inputs.

**Comment by dakorpar** [comment]
@mskocik You want to create PR against  https://github.com/contributte/forms-bootstrap
since it's not a fork you can't do it directly, but you can just clone repo copy your files over and create PR.
current master is 1:1 with this...
I can also do it but then your name in commits won't be visible ;)

**Comment by mskocik** [comment]
You can do it commit changes my previous together with your DateTime 
fix. You are the maintainer now :)

**Comment by chapcz** [comment]
Cool, thanks. Will it be also available via the composer as `contributte/forms-bootstrap` ?

**Comment by dakorpar** [comment]
yep, I'm just preparing everything.
there will be some BCs, since there are a lot of breaks of coding standards, like constant being in camel case and some other minor things.
It will support only nette 3.0+ and it will be under \Contributte\FormsBootstrap namespace.
Soon it's going to be available,
you can try it out even now if you add to composer:

```
	"repositories": [
		{
			"type": "vcs",
			"url": "https://github.com/contributte/forms-bootstrap"
		}
	]
.
.
.

      	"contributte/forms-bootstrap": "dev-master",
```

**Comment by dakorpar** [comment]
v0.1 has been released, so you can use it.
https://github.com/contributte/forms-bootstrap
