### ISSUE TITLE
Přepnuti mode na Enums\RenderMode::SideBySideMode)

### ISSUE THREAD

**Issue by netmoleCZ** [czubehead/bootstrap-4-forms#3]
dobrý den jak se přepínají mody  ?

**Comment by czubehead** [comment]
Zdravím, asi takto: `$form->renderMode= RenderMode::SideBySideMode;`.
Případně je to také vlastnost `mode` na `BootstrapRenderer`u
Pozn.: tohle není úplně něco, co patří na issues, dole je kontakt, nebo přímo na GitHub profilu :)
