### ISSUE TITLE
setHtmlAttribute("class", "foo")

### ISSUE THREAD

**Issue by multimonty** [czubehead/bootstrap-4-forms#6]
Ahoj.

V nové verzi bohužel ta samá chyba :(
Při použití pokusu přidání třídy inputu vyskakuje chyba
"[] operator not supported for strings"

**Comment by czubehead** [comment]
V tom případě budu potřebovat větší kus kódu, ideálně vytvoření formuláře a přidání inputu.

**Comment by czubehead** [comment]
Aha, už jsem našel chybu. Nejsem si jist, jestli je to bug, jako spíše porušení konvencí knihovny - knihovna všude používá pro třídu pole, a proto se to rozbije, pokud tomu dáš string.
Správně by se to mělo udělat takto:
```php
setHtmlAttribute('class',['foo']);
```

**Comment by seegr** [comment]
Aha, no vidíš, to mě nenapadlo, původní Form se s tím popere.
Každopádně díky za objasnění ;)

**Comment by czubehead** [comment]
Původní form totiž tu třídu nemodifikuje.

**Comment by czubehead** [comment]
Snad konečně opraveno díky c0cf066a06718d109586034186edb401c82be6a1 . Je dost možné, že to někde není ošetřené, proto nechávám vlákno otevřené.
