### ISSUE TITLE
Ignored parameters

### ISSUE THREAD

**Issue by JerabekJakub** [czubehead/bootstrap-4-forms#7]
Hi, why do you have parameters in your functions when you are ignoring them?
For example [here](https://github.com/czubehead/bootstrap-4-forms/blob/master/src/Traits/BootstrapContainerTrait.php#L253).  It took me some time to figure out why it does not take effect.
Thank you.

**Comment by czubehead** [comment]
Because PHPStorm and often PHP itself will scream they have to be there because of how PHP inheritance works. Signature cannot be changed, unfortunately.
If you suggest any better way, I'm all ears.

**Comment by czubehead** [comment]
Actually, why not use 'em, right? They are used now.

**Comment by JerabekJakub** [comment]
Thank you. You forget to delete "ignored" in javadoc. :)
